# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  jackalope.io:
    env:
      db_password: jackalope_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "Ty[h/^&ZO30s0;tU5`GgYyHCVy9ZYITLO-7l)o|a^o#|?STg}UA/^yVJxK6[FoAu"
      secure_auth_key: "r%amX3,iI-tRT$a7{6fo_qF.^Y7yyGxc,.`dGBe;Ta7[zqln$^NH$W6/;FYCQES`"
      logged_in_key: "t3&J`?!*`}a70dVwcU<jrZH9d2]JGJqLhYW;?O@sS+$U^?ya@4SH:C3op?JA,@@o"
      nonce_key: "#rb=9*:O$bW$,Pv+gRlSTgnW^}8YOeG_3H=_/m0%gdOPiyVQnK5Jz[|lKEwUP^)g"
      auth_salt: "F|Sq:!K[w>{MGv$|uQ=Ujx!|IX<vmn_*GfMLgv#T{<+Bj]]^4+[s^]KG&Tv|OV*e"
      secure_auth_salt: "I<7t4p=fy>M5)t,7IB@9Jaoj)Rz9/X7VW$SUF@niZpm(ZxAh4X6lu)=vPZB*qH6`"
      logged_in_salt: "-3.mZiN`tjRG=j$.YjDj4b0u95hmI>bHx79yY0X!D]9iqs@5^.g0p*&s6V/;lO_U"
      nonce_salt: "IpV;|0%n^KVSu#0:`_{D&Om_O;qJ*afzE/}{3&EH0Y#oS:Y/g9)39SQiPE9DTC:S"
